[Model]
Scale = 1               # 1e3=meter, 1=mm, 25.4=inch
z0 = 0
UseBSpline = false
r_z = [
    [-2.0, 1.0],
    [0.0, 1.0],
    [1.5, 0.25],
    [2.0, 0.25]]

[[Output]]
Type = 'STL'
LinearDeflection = 0.1   # mm
IsRelative = false
AngularDeflection = 10.0  # deg
Filename = 'conical.stl'

[[Output]]
Type = 'STEP'
Filename = 'conical.stp'
